### ISSUE TITLE
can custom rules be added?

### ISSUE THREAD

**Issue by ciel** [Hypercubed/angular-marked#58]
I know that in the marked library, you can forcefully code in custom rules by modifying the source - is it possible to do this a bit cleaner in angular-marked? Is there a way to add rules to the lexer at configuration? 

I'm wanting to add a rule to turn...

`[!alert::warning] > blockquote text`

into...

`<blockquote class="alert alert-warning">Some text goes here as a warning.</blockquote>`

But am having a hard time figuring out where I can add this in without having to muck around and change the internal plumbing of both marked and angular-marked.

**Comment by Hypercubed** [comment]
There is nothing extra built into angular-marked.  Look into overriding the marked renderer.  https://github.com/Hypercubed/angular-marked/blob/master/README.md#override-rendered-markdown-links

**Comment by ciel** [comment]
That only lets you override the implementation of an existing rule, though. Is it possible to use that to add completely new rules?

**Comment by Hypercubed** [comment]
I think you will have to look at marked.

**Comment by Hypercubed** [comment]
Reopen if you still think this is an angular-marked issue.

**Comment by diegopso** [comment]
I runned into the same issue. The problem is that you only allow the Renderer to be overwritten (via `markedProvider.setRenderer`). However one cannot overwritte the Lexer and InlineLexer.  In my case I wanned to add a rule to mention, as somethig like `/^@[0-9a-zA-Z]+/` and render it appropriately.


Maybe reading this thread makes it more clear: https://stackoverflow.com/questions/26507341/how-to-write-custom-inlinelexer-rule-for-marked-js .
